id: AE3DBF783
title: A Daily Long-Life Practice of Amitāyus
type: translation
pechas:
- I27D1D6D3
- I5D47D785
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:11.973291
  last_modified_at: 2023-01-04 11:49:11.973303
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I27D1D6D3/43F0: 493F
  I5D47D785/233F: 493F
